# This is a basic workflow to help you get started with Actions

name: Test Workflow

on:
  push:
    branches: [ main, developer ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:      
        username: filipesilvadev
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
      with:      
        # o contexto de onde essa action esta sendo executada
        # o ponto '.' indica que irá procurar pelo DockerFile na raiz deste repositório
        context: .
        # List of tags referente a esta imagem
        tags: filipesilvadev/fiap-githubactions:latest        
        push: true
              
